# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        methods:  GET
        id: \d+